### PR TITLE
✨🔨 Add Dockerfile & docker-compose.yml

### PR DESCRIPTION
**Pull request by naton0**
I can help with Github Actions too

### CODE REVIEW

**Comment by KokosnussDEV** [comment]
Thanks for your contribution!
Did you test this with a higher node version so we could use a "newer" one?

**Comment by KokosnussDEV** [comment]
It would also be useful to also provide a database inside the container or to use a seperate one and connect them using docker-compose ^^

**Comment by naton0** [comment]
I added docker-compose but without #36 the url-shortener container needs a restart after the first creation. 

> Did you test this with a higher node version so we could use a "newer" one?
I changed the node version to 14.16.

**Comment by KokosnussDEV** [comment]
The process will now error if the db connection errors

**Comment by KokosnussDEV** [comment]
@all-contributors please add @naton0 for platform

**Comment by KokosnussDEV** [comment]
You said you would also help out with workflows? If you are still up to do that please do!
Quick checklist for the workflow:

- [ ] Build image
- [ ] publish the image to:
  - [ ] Docker Hub
  - [ ] GitHub Packages

**Review by KokosnussDEV — APPROVED** [review]

**Review by jxn-30 — APPROVED** [review]

**Pull request merged**
